CRITICAL - 2025-08-04 15:17:40 --> Error: Undefined constant "routes"
[Method: GET, Route: empleados]
in APPPATH\Config\Routes.php on line 14.
 1 SYSTEMPATH\Router\RouteCollection.php(339): require()
 2 SYSTEMPATH\CodeIgniter.php(821): CodeIgniter\Router\RouteCollection->loadRoutes()
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 15:17:40 --> Error: Undefined constant "routes"
[Method: GET, Route: empleados]
in APPPATH\Config\Routes.php on line 14.
 1 SYSTEMPATH\Router\RouteCollection.php(339): require()
 2 SYSTEMPATH\CodeIgniter.php(821): CodeIgniter\Router\RouteCollection->loadRoutes()
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 15:42:29 --> CodeIgniter\HTTP\Exceptions\HTTPException: The route for "vista_empleados" cannot be found.
[Method: GET, Route: eliminar_empleado/502]
in SYSTEMPATH\HTTP\RedirectResponse.php on line 63.
 1 SYSTEMPATH\HTTP\RedirectResponse.php(63): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('vista_empleados')
 2 APPPATH\Controllers\EmpleadoController.php(37): CodeIgniter\HTTP\RedirectResponse->route(false)
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->eliminar('502')
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:45:25 --> mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `em...', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `em...')
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `em...')
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `em...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(1152): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(35): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->eliminar('501')
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-04 15:45:25 --> CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away
[Method: GET, Route: eliminar_empleado/501]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `empleados`
WHERE `empleado_id` IN :empleado_id:', [...], false)
 2 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 4 APPPATH\Controllers\EmpleadoController.php(35): CodeIgniter\BaseModel->delete([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->eliminar('501')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 15:45:25 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `empleados`
WHERE `empleado_id` IN (\'501\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `empleados`
WHERE `empleado_id` IN (\'501\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `empleados`
WHERE `empleado_id` IN :empleado_id:', [...], false)
 4 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 6 APPPATH\Controllers\EmpleadoController.php(35): CodeIgniter\BaseModel->delete([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->eliminar('501')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 15:45:25 --> [Caused by] mysqli_sql_exception: MySQL server has gone away
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('DELETE FROM `empleados`
WHERE `empleado_id` IN (\'501\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `empleados`
WHERE `empleado_id` IN (\'501\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `empleados`
WHERE `empleado_id` IN (\'501\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2848): CodeIgniter\Database\BaseConnection->query('DELETE FROM `empleados`
WHERE `empleado_id` IN :empleado_id:', [...], false)
 5 SYSTEMPATH\Model.php(521): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1152): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\EmpleadoController.php(35): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->eliminar('501')
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:45:44 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:45:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:45:51 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:45:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:45:54 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:45:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:47:53 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `em...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(27): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregarEmpleado()
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `em...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(27): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregarEmpleado()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-04 15:47:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: POST, Route: agregarEmpleado]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `empleados` (`empleado_id`, `nombre`, `apellido`, `telefono`, `puesto_id`, `fecha_nacimiento`) VALUES (:empleado_id:, :nombre:, :apellido:, :telefono:, :puesto_id:, :fecha_nacimiento:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\EmpleadoController.php(27): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->agregarEmpleado()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:47:55 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:47:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:48:05 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:48:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:48:38 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:48:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:48:43 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:48:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:50:41 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:50:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:50:59 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:50:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:52:06 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:52:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 15:52:37 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 15:52:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 15:55:55 --> ParseError: syntax error, unexpected token "}", expecting ";"
[Method: GET, Route: empleados]
in APPPATH\Controllers\EmpleadoController.php on line 38.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\fs2025\\codeigniter4-inventario\\app\\Controllers\\EmpleadoController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\EmpleadoController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\EmpleadoController')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\EmpleadoController', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 15:56:53 --> ParseError: syntax error, unexpected token "}", expecting ";"
[Method: GET, Route: empleados]
in APPPATH\Controllers\EmpleadoController.php on line 38.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\fs2025\\codeigniter4-inventario\\app\\Controllers\\EmpleadoController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\EmpleadoController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\EmpleadoController')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\EmpleadoController', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 16:04:20 --> ParseError: syntax error, unexpected token "(", expecting identifier or variable or "{" or "$"
[Method: GET, Route: empleados]
in APPPATH\Controllers\EmpleadoController.php on line 37.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\fs2025\\codeigniter4-inventario\\app\\Controllers\\EmpleadoController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\EmpleadoController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\EmpleadoController')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\EmpleadoController', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 16:11:59 --> ParseError: syntax error, unexpected token ";", expecting "function" or "const"
[Method: GET, Route: empleados]
in APPPATH\Controllers\EmpleadoController.php on line 13.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\fs2025\\codeigniter4-inventario\\app\\Controllers\\EmpleadoController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\EmpleadoController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\EmpleadoController')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\EmpleadoController', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 17:04:30 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 17:04:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-04 17:04:39 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'fs2025_inventar...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2025\codeigniter4-inventario\app\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
#7 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#8 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2025\codeigniter4-inventario\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2025\codeigniter4-inventario\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-04 17:04:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: empleados]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `empleados`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\EmpleadoController.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:04:58 --> Error: Undefined constant "datos"
[Method: GET, Route: buscar_empleado/1]
in APPPATH\Views\form_modificar_empleado.php on line 16.
 1 SYSTEMPATH\View\View.php(226): include()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_empleado', [], true)
 4 APPPATH\Controllers\EmpleadoController.php(45): view('form_modificar_empleado', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->buscar('1')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:05:28 --> Error: Undefined constant "datos"
[Method: GET, Route: buscar_empleado/500]
in APPPATH\Views\form_modificar_empleado.php on line 16.
 1 SYSTEMPATH\View\View.php(226): include()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_empleado', [], true)
 4 APPPATH\Controllers\EmpleadoController.php(45): view('form_modificar_empleado', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->buscar('500')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:06:22 --> Error: Undefined constant "datos"
[Method: GET, Route: buscar_empleado/500]
in APPPATH\Views\form_modificar_empleado.php on line 16.
 1 SYSTEMPATH\View\View.php(226): include()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_empleado', [], true)
 4 APPPATH\Controllers\EmpleadoController.php(45): view('form_modificar_empleado', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->buscar('500')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:06:23 --> Error: Undefined constant "datos"
[Method: GET, Route: buscar_empleado/500]
in APPPATH\Views\form_modificar_empleado.php on line 16.
 1 SYSTEMPATH\View\View.php(226): include()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_empleado', [], true)
 4 APPPATH\Controllers\EmpleadoController.php(45): view('form_modificar_empleado', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->buscar('500')
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:12:18 --> ParseError: syntax error, unexpected end of file
[Method: GET, Route: eliminar_empleado/501]
in APPPATH\Config\Routes.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(821): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:22:23 --> ParseError: syntax error, unexpected token ";"
[Method: GET, Route: buscar_empleado/1]
in APPPATH\Views\form_modificar_empleado.php on line 15.
 1 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_empleado', [], true)
 3 APPPATH\Controllers\EmpleadoController.php(45): view('form_modificar_empleado', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->buscar('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:27:16 --> ParseError: Unmatched ')'
[Method: GET, Route: buscar_empleado/1]
in APPPATH\Views\form_modificar_empleado.php on line 15.
 1 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_empleado', [], true)
 3 APPPATH\Controllers\EmpleadoController.php(45): view('form_modificar_empleado', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->buscar('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-04 17:27:20 --> ParseError: Unmatched ')'
[Method: GET, Route: buscar_empleado/1]
in APPPATH\Views\form_modificar_empleado.php on line 15.
 1 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('form_modificar_empleado', [], true)
 3 APPPATH\Controllers\EmpleadoController.php(45): view('form_modificar_empleado', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\EmpleadoController->buscar('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
